// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzmmqyqsqvfuinebuffl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6bW1xeXFzcXZmdWluZWJ1ZmZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0ODE4MjIsImV4cCI6MjA3MzA1NzgyMn0.zd8vb-3erZVcv0EP3-srj_0HlH6fQ3t11X271puZ7lE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});